name: CoreProelium
main: fr.froz.proelium.Main
version: 0.4
description: Zbeub
author: MrFroz
commands:
  warn:
    description: Avertissement.
    usage: /warn
  help:
    description: help.
  plugins:
    description: pl.
  pl:
    description: pl.  
  menu:
    description: menu.
  pub:
    description: pub
  staff:
    description: staff
    

    